### ISSUE TITLE
[Bug]: Filter error in customer list if a manual segment is created

### ISSUE THREAD

**Issue by danielerne** [pimcore/customer-data-framework#258] opened 2022-02-04 13:47 UTC
### Expected behavior

Customer list shows results according to segment filters

### Actual behavior

An error is throw
<img width="1476" alt="Filter Segment Error" src="https://user-images.githubusercontent.com/546931/152539342-e9af47e0-295c-46a7-8656-f3a816bd1a5b.png">
n

### Steps to reproduce

Create a manual segment with "Show as filter"
Add the segment to the customer
Open customer list and select the segment filter

**Comment by dvesh3** [comment] 2022-02-15 16:53
@danielerne works for me 
![image](https://user-images.githubusercontent.com/5137917/154109628-d4b9a60f-04c5-4f04-965c-5a2a8ca06d4d.png)

**Comment by dvesh3** [comment] 2022-02-21 09:22
@danielerne 🏓

**Comment by danielerne** [comment] 2022-02-21 10:42
@dvesh3 Yes, I need to check it again with the latest release. I will let you know very soon.

**Comment by danielerne** [comment] 2022-03-02 10:43
@dvesh3 It works on demo.pimcore.com but on our implementation it doesn't work. Do you have any idea what is causing this error? We have Pimcore 10.3.1

<img width="1620" alt="Bildschirmfoto 2022-03-02 um 11 41 36" src="https://user-images.githubusercontent.com/546931/156346378-94ba000e-0400-477b-b179-aee225d02e1b.png">

**Comment by dvesh3** [comment] 2022-03-02 12:38
@danielerne Eventually, I was able to reproduce the issue by adding localizedfields to the Customer Class. I'm not quite sure where the issue is coming from, so have to debug the request to list action with filters.

**Comment by danielerne** [comment] 2022-03-02 12:51
@dvesh3 Yes, I was able to figure out the line. 
It is in the CustomerSegment.php Line 213 at CustomerManagementFrameworkBundle\CustomerList\Filter

If I manually change the table name it works.
<img width="886" alt="Bildschirmfoto 2022-03-02 um 13 50 28" src="https://user-images.githubusercontent.com/546931/156364982-b57023cc-f15b-4e42-848c-b442ad3b4b69.png">

**Comment by dvesh3** [comment] 2022-03-09 09:08
Fixed by #272

**Closed as completed by dvesh3** 2022-03-09 09:08 UTC
Labels: Bug
