### ISSUE TITLE
[SegmentAssignment] saving object when class assignment not active throws error in console

### ISSUE THREAD

**Issue by fashxp** [pimcore/customer-data-framework#17] opened 2017-10-11 09:51 UTC
TypeError: Cannot read property 'breaksInheritance' of undefined
    at klass.saveSegmentAssignments (startup.js?_dc=1:284)
    at klass.preSaveObject (startup.js?_dc=1:279)

**Comment by Kzumueller** [comment] 2017-10-24 13:08
I couldn't reproduce this issue, 
however the saving process is now decoupled from the pimcore save button
and now happens whenever data in the assignment tab is saved.

fixed in 264180d

**Closed by Kzumueller** 2017-10-24 13:08 UTC
Labels: Bug
